### ISSUE TITLE
question about shape of ground truth density map, and train.prototxt

### ISSUE THREAD

**Issue by yypeng9468** [miao0913/SaCNN-CrowdCounting-Tencent_Youtu#16]
Sorry to bother, but I have one question about the shape of ground truth density map in this repo.
You say in your essay that the output density map if 1/8 of the input image, so is it necessary for me to downsample my density map by factor 8. And if I want to prepare my data in lmdb format, I should turn the ground truth csv  into density map picture, right?

<img width="585" alt="wechatimg303" src="https://user-images.githubusercontent.com/39260249/44382053-e1895380-a545-11e8-841a-73acd98399a0.png">

**Comment by miao0913** [comment]
yes. you need to downsample it by 8. And the prototxt we provide requires an input of lmdb formate for both density map and image.
