### ISSUE TITLE
Do u have WorldExpo’10 crowd counting dataset link ?

### ISSUE THREAD

**Issue by zhuqiang00099** [miao0913/SaCNN-CrowdCounting-Tencent_Youtu#18]
do u have labeled WorldExpo’10 crowd counting dataset?

**Comment by alercelik** [comment]
Could you share if you found it? Authors did not respond to my e-mail.

**Comment by yangtle** [comment]
> Could you share if you found it? Authors did not respond to my e-mail.
Hello, have you found the dataset, can you contact you to share it? Can be paid. Thank you so much!
