### ISSUE TITLE
error i met when running the crowdtest.m

### ISSUE THREAD

**Issue by ying135** [miao0913/SaCNN-CrowdCounting-Tencent_Youtu#6]
Before using SaCnn to train, I want to test it.But I met some error, hoping that u can help me.Thank you very much!
This is the error I met in the run time of crowdtest.m when i run test_sacnn.sh :

malloc: unknown:0: assertion botched
free: called with unallocated block argument
last command: (null)
Aborting...LD_LIBRARY_PATH=/usr/local/lib/home/code/yuying/caffe-master/build/tools/extract_features /home/code/yuying/SaCNN/model/Part_B/ShanghaiTech_part_B.caffemodel deploy.prototxt estdmap estdmap.db 10 lmdb GPU 2: Aborted

Actually, and I'm not familiar with matcaffe,.There are some code I don't understand.
system([lib caffe_path ' ' caffe_model ' deploy.prototxt estdmap estdmap.db ' num2str(nImg) ' lmdb GPU ' num2str(gpu_id)]);
system([lmdb2txt ' estdmap.db >> estdmap.txt']);
Can u explain it?Or can u tell me what should i do to understand it?

Thank u very much!Best wishes!

**Comment by ying135** [comment]
And i have tried runing "LD_LIBRARY_PATH=/usr/local/lib/home/code/yuying/caffe-master/build/tools/extract_features /home/code/yuying/SaCNN/model/Part_B/ShanghaiTech_part_B.caffemodel deploy.prototxt estdmap estdmap.db 10 lmdb GPU 2"in the terminal.But there are some thing unreadable like this, ▒zON</>▒:▒▒:9▒▒ۻ▒3A▒▒▒2▒▒▒▒J-|▒'▒;▒▒▒&▒▒ż▒=}▒UJ.▒▒▒▒▒▒▒;▒(▒;ɪ:▒▒▒L▒▒▒▒▒        ▒▒   .
So i insert a space after "LD_LIBRARY_PATH=/usr/local/lib/",then the error is:

[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 10:11: Non-repeated field "source" is specified multiple times.
F0518 22:20:14.063143 46584 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: deploy.prototxt
*** Check failure stack trace: ***
    @     0x7fbf989f23da  google::LogMessage::Fail()
    @     0x7fbf989f231e  google::LogMessage::SendToLog()
    @     0x7fbf989f1c5a  google::LogMessage::Flush()
    @     0x7fbf989f577b  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fbf9884b5b1  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7fbf987dc785  caffe::Net<>::Net()
    @           0x40ad19  feature_extraction_pipeline<>()
    @     0x7fbf97b50830  __libc_start_main
    @           0x405369  _start
    @              (nil)  (unknown)
Aborted (core dumped)

Looking forward to yout reply!Thanks!

**Comment by kimparksama** [comment]
Hi,I met the same error, could you tell me the way to solve it? thanks @ying135
